### ISSUE TITLE
Ensure address decodes to exactly 24 bytes

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/BitShares-JS#33]
Looking at your address code [1] makes me think you accept, and possibly generate, addresses which are not correctly padded.  If you do not generate padding correctly, then there is a 1/256 chance an address will be incompatible with the current client, which does not, and will not, accept incorrectly padded addresses [2].

Please review your code's behavior when dealing with addresses which require padding!

[1] https://github.com/BitShares/BitShares-JS/blob/001e47673c6056c138d083eaf5558864bfb8d1fd/src/ecc/address.coffee

[2] https://github.com/BitShares/bitshares/issues/1274

**Comment by jcalfee** [comment]
The hashes (address) mostly sit around as a buffer objects of the exact size and get hashed that way as data.  They are always the exact size (in bits).  When we get around to padding, the bs58 library handles the case where the hash starts with zeros and padding may be needed:  

https://github.com/cryptocoinjs/bs58/blob/2.0.0/lib/bs58.js#L39-L40

It is used here: https://github.com/BitShares/BitShares-JS/blob/v0/src/ecc/address.coffee#L47

Thanks for pointing this out, it is not obvious...  You can see similar code in bitcoinjs-lib where they are hashing with the same library we use then passing that directly to create an Address object:
```
// Operations
ECPubKey.prototype.getAddress = function(network) {
  network = network || networks.bitcoin

  return new Address(crypto.hash160(this.toBuffer()), network.pubKeyHash)
}
```

```
function Address(hash, version) {
  typeForce('Buffer', hash)
  assert.strictEqual(hash.length, 20, 'Invalid hash length')
```
