### ISSUE TITLE
Cannot dump "Withdraw" instance with toHex() -> "truncated"

### ISSUE THREAD

**Issue by xeroc** [BitShares/BitShares-JS#37]
Hey there, I am running a slightly modified version of bitshares-js from 
pull request #36 to expose the blockchain class to the browser.

I also added some required methods to dump "toHex()" properly.

However, this is the commands I can execute:

    wc=bts.blockchain.WithdrawCondition.fromJson({ "asset_id":22, "slate_id":0,
    "type":"withdraw_signature_type", "data":{
     "owner":"XTS8QZgeFurRa6hzZVDtUDfvg7u7LAySeuNK", "memo":{
      "one_time_key":"XTS54pK2P15bth1C4v9QLtMQDuV7vR8RQQttMBHMzScrJdG7GsBza",
      "encrypted_memo_data":"" }}})
    Object { asset_id: 22, slate_id: 0, type_id: 1, condition: Object }
    wc.toHex()
    "1600000000000000000137513dbafc2b1e175d91e3d7d71181b9742fdf90dc01021772ca67d26ed39f30580bb7e2ac5952bba74de08db7246b19c7ad0ae439280e00"

    deposit = new bts.blockchain.Deposit(10000, wc)
    deposit.toHex()
    "10270000000000001600000000000000000137513dbafc2b1e175d91e3d7d71181b9742fdf90dc01021772ca67d26ed39f30580bb7e2ac5952bba74de08db7246b19c7ad0ae439280e00"

    balanceid = '\xd9\xc7H\xd2[\x80\xe7\x80\x13\xfa\xe5W\x1d\xd6\xb84\xc7`\xda'
    withdraw = new bts.blockchain.Withdraw(balanceid,6000,"")

A

    withdraw.toHex()

fails with message

    Error: [truncated]

What am I doing wrong?

ps. the balanceid is the binary representation of (python repr) of the
base56checkdecoded (BTS version) of a XTS balance_id.

**Comment by jcalfee** [comment]
You have to get the data types just right then your constructing the objects.  So, make sure your using a buffer where a buffer is needed, etc...  Here is an example:

https://github.com/BitShares/BitShares-JS/blob/v0/scratchpad/trx_titan.coffee#L166-L170

Do you have access to the buffer object?  You may need another fromJson if you can't get the buffer object.

**Comment by xeroc** [comment]
withdraw = new bts.blockchain.Withdraw(balanceid,6000,[0x0]) 

is working like a charm :)
