### ISSUE TITLE
Cold wallet support

### ISSUE THREAD

**Issue by jcalfee** [bitshares/BitShares-JS#65]

**Comment by xeroc** [comment]
Do you plan to integrate encrypted privkeys ala bip38?

**Comment by jcalfee** [comment]
Thank you, I'll look into that.  We do encrypt all private keys already before storage.  

I'm thinking about support for an active-key only online wallet.  For the cold wallet, we could have a way to run the java-script from a downloaded package (instead of the web) for the purpose of creating the owner key.

**Comment by jcalfee** [comment]
https://github.com/BitShares/web_wallet/commit/d22dae3376500c7de053a5600ff0c51aafc68b80

**Comment by xeroc** [comment]
I am thinking of having a feature that can sweep a bip38 encrypted paperwallet

**Comment by xeroc** [comment]
could we have a optional QR-code scanner built into every text form that accepts either a BTS address / pubkey or private key?

something like this: 

* https://github.com/LazarSoft/jsqrcode
* https://developer.tizen.org/documentation/articles/barcode-generator-and-scanner

**Comment by jcalfee** [comment]
Addressing in Graphene....
