### ISSUE TITLE
Could wallet.bitshares.org/rpc be extended to a API server

### ISSUE THREAD

**Issue by xeroc** [BitShares/BitShares-JS#80]
Hey James,

just wanted to kindly ask, if there are any plans to make wallet.bitshares.org/rpc available for other websites .. I am thinking of something similar to brainwallet.org that fetches "unspent outputs" or the address balances from a API server/blockchain explorer .. 

It would require origin headers:

* http://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

and an rpc-wrapper for commands in the url as you proposed here https://github.com/BitShares/bitshares/issues/1441

**Comment by jcalfee** [comment]
There are three things off the top of my head: account lockups, balance record lockups, and transactions.   Accounts and balance records can change but currently, transactions are verified only and can only increase in number.  

For a public API we need to transition from polling to web sockets, however, I don't see that happening until after bitshares-js is as functional as the native client or something amazing happens and the volume goes up so much that we need this.  In other words, if we simply white list some rpc calls (with the same origin header) we are just asking for more polling...

So, for now, maybe we can let just your server do less than ideal polling.  You should consider doing a better job instead.  I'll temp you to look at Bytemasters new code in DevShares.  There is a websockts library and support for a new websockets port.  I believe it is generically done for all RPC calls you should consider that it is just an example and not complete.  Let me know what you think...

**Comment by xeroc** [comment]
I will read into web sockets .. (have out-dated web knowledge) 
and thanks for considering all my issues :)

Gonna take a look at devshares code

**Comment by jcalfee** [comment]
I have an idea for a simple websocket implementation.  Any wallet or client could register a list of public addresses (like the owner and active key on each account) as a transaction listener.  Any transaction that gets included in the blockchain that matches a registered address will be sent to the listener (the client).

In this way, the client will know if any of the three happened: account record changed, balance record changed, or a new transaction appeared.  Some transaction types will prompt the client to re-query the server.  It does not force someone to do it correctly, however, we can certainly detect over-polling.  I this this is a good step to take, it should be very easy to implement.

**Comment by xeroc** [comment]
> In this way, the client will know if any of the three happened: account record changed, balance record changed, or a new transaction appeared. Some transaction types will prompt the client to re-query the server. It does not force someone to do it correctly, however, we can certainly detect over-polling. This should be very easy to implement improve our scalability.

Sounds good to me .. we currently lack the possibility to get notified on address related stuff ..

But this doesn't really help for the OP. We lack a public API to the blockchain. Something that I can poll/interface to get price updates for a ticker, or get a address balances just once i.e. for a cold storage solution or a transaction builder that just needs the balance ids, assets and amount of an address. 

For my application, I don't need regular polling but just an interface to get information out of the blockchain to do something else with it.

But i totally agree with you on the issues with polling and that we need websockets.

I will close this issue for now and either wait for the web socket implementation or find another solution when I get the time to (not so soon, anyway).
