### ISSUE TITLE
Live switching between BTS and DVS

### ISSUE THREAD

**Issue by xeroc** [BitShares/BitShares-JS#82]
Can we have a dropdown menu/switch to go from the BitShares network into the DevShares or NOTEs network eventually?

Related discussion:
https://bitsharestalk.org/index.php/topic,14433.msg202236.html#msg202236

**Comment by jcalfee** [comment]
We can probably do something like devshares_wallet.bitshares.org or dvs_wallet.bitshares.org, this will help test everything.  I'm sure NOTEs will be better off maintaining their server and upgrades due to there own features, release schedules, and code base.

**Comment by xeroc** [comment]
Cool .. Thanks.

But would it also be possible to switch from both chains from WITHIN the wallet?
Much like switching accounts in a bank account? I recall you have added the 'config' class to the set of globally available classes .. 

Maybe I need to dig a little deeper into how the connection to the bts client is done in the web wallet

**Comment by jcalfee** [comment]
It will keep both databases separate, however, two wallets will almost always be on different version.  Also, you really need to use a different recovery key on the two networks because there a lot less restrictions on DevShares.  You might as well have a link.

**Comment by xeroc** [comment]
understood
