### ISSUE TITLE
Adding Export Wallet to json menu/button

### ISSUE THREAD

**Issue by clayop** [BitShares/BitShares-JS#83]
If possible, can you add "Export Wallet (to json)" menu for those who want store their wallet in their local computer or usb?
Now it is possible by using wallet_export_to_json, as shown in http://www.bts.hk/bts-web-wallet.html 
But if the web wallet provides this function in a easier way, it would be great.

**Comment by jcalfee** [comment]
Moved to the web_wallet repository..

**Comment by jcalfee** [comment]
We have an advanced screen already.  I can add a wallet export button there.
