### ISSUE TITLE
Why CoffeeScript?

### ISSUE THREAD

**Issue by hackingbeauty** [BitShares/BitShares-JS#87]
Why oh why would you write this in CoffeeScript?

**Comment by xeroc** [comment]
> Why oh why would you write this in CoffeeScript?

I don't see the problem here. Would you rather write JS directly? That's just gonna be a mess.
What's your point?

**Comment by jcalfee** [comment]
There are legacy reasons.  CoffeeScript still involves less typing and has some great tricks.  It has trimmed the fat on a syntax level but there are some undesired complexities.  I can say, we are doing more es6.  So far, I'm finding es6 very well though out and without subtle gotchas.  Some things just will not be the same.
