### ISSUE TITLE
Can't issue blockchain_list_address_balances on address in console

### ISSUE THREAD

**Issue by xeroc** [bitshares/BitShares-JS#88]
Hi  James,

a redditor asked to have a way to confirm an address balance. However it seems that the wallet.bitshares.org client does not answer properly on `blockchain_list_address_balances`. What could be the reason?

http://www.reddit.com/r/BitShares/comments/3912fd/new_to_bitshares_wallet_problem/cs0eedx?context=3

**Comment by jcalfee** [comment]
I white-listed `blockchain_list_address_balances`.  Also, when a command is not white-listed, the console will report "Unauthorized."
