### ISSUE TITLE
BTS_BLOCKCHAIN_MAX_MEMO_SIZE is not 51

### ISSUE THREAD

**Issue by wildbunny** [bitshares/bitshares-js#92]
Just creating an official issue if there isn't already one. The memo length is still set to 19 characters in https://github.com/bitshares/bitshares-js/blob/eb9daab241be6da39be7fea583b93ab7a93b27d3/src/blockchain/config.coffee

**Comment by jcalfee** [comment]
Believe me, I really wish it were this simple I would do it.  I know several people have asked for this.  It is called an extended memo and requires a transaction change.

We are getting very close to having full BTS 2.0 transaction support in JavaScript making this code base obsolete so the effort here will not have a chance to payoff..
